services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres
    volumes:
      - ./:/app
    networks:
      - app_network
volumes:
  postgres_data:
networks:
  app_network:
    driver: bridge
